### ISSUE TITLE
Suggestion: move the contents of bidirectional_scroll_view up one directory

### ISSUE THREAD

**Issue by sethladd** [toufikzitouni/flutter-bidirectional_scrollview_plugin#2]
Normally, the root of the GitHub repo contains the package contents (lib, test, example, etc).

It's not a big deal, but we suggest that you move flutter-bidirectional_scrollview_plugin/bidirectional_scroll_view/* up into flutter-bidirectional_scrollview_plugin

Thanks!

**Comment by toufikzitouni** [comment]
Yep! done
