### ISSUE TITLE
Please upgrade flutter SDK version

### ISSUE THREAD

**Issue by NewITCorp** [toufikzitouni/flutter-bidirectional_scrollview_plugin#5]
Please upgrade flutter SDK version.

The current Dart SDK version is 2.1.0-dev.1.0.flutter-ccb16f7282.

Because bidirectional_scroll_view 0.0.5 requires SDK version <2.0.0 and no versions of bidirectional_scroll_view match >0.0.5 <0.1.0, bidirectional_scroll_view ^0.0.5 is forbidden.
So, because MyProject1 depends on bidirectional_scroll_view ^0.0.5, version solving failed.
pub get failed (1)

thanks!

**Comment by efortuna** [comment]
I made a Pull request to fix this: https://github.com/toufikzitouni/flutter-bidirectional_scrollview_plugin/pull/6

Alternatively, you can just point to my fork until the pull request is accepted: https://github.com/efortuna/flutter-bidirectional_scrollview_plugin

**Comment by NewITCorp** [comment]
Oh, Hi Emily.
Thanks for your help.
I may close an issue because I no longer use this library. (i use paginated datatable instead)
I will learn how you fix it soon or later.
