### ISSUE TITLE
Fix dependencies in pubspec.yaml.

### ISSUE THREAD

**Issue by Moanrisy** [toufikzitouni/flutter-bidirectional_scrollview_plugin#9]
Running flutter packages pub upgrade failed with the following output:

ERR: The current Dart SDK version is 2.2.1-dev.0.0.flutter-7c70ab1817.
 
 Because bidirectional_scroll_view requires SDK version >=1.19.0 <2.1.0, version solving failed.

Can you help me fix this please?

**Comment by The-Redhat** [comment]
I made a pr [#10](https://github.com/toufikzitouni/flutter-bidirectional_scrollview_plugin/pull/10)

**Comment by xqdd** [comment]
### For temporary use
> ### <s>newese</s>  
> ### newest 
![image](https://user-images.githubusercontent.com/20871761/56454253-892e7e00-6380-11e9-85e1-f570aa18e891.png)

**Comment by The-Redhat** [comment]
My pr to fix this issue was merged, but the author didn't push the new version to pub. You can simply use the GitHub version.

**Comment by The-Redhat** [comment]
This issue can be closed. The plugin works with the newest version of flutter.
